# Generated by Django 2.2.14 on 2020-09-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0002_triggers'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vmhistory',
            name='vm_history_changed_by',
        ),
        migrations.RemoveIndex(
            model_name='vpnhistory',
            name='vpn_history_changed_by',
        ),
        migrations.RenameField(
            model_name='vmhistory',
            old_name='changed_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='vpnhistory',
            old_name='changed_by',
            new_name='modified_by',
        ),
        migrations.AddIndex(
            model_name='vmhistory',
            index=models.Index(fields=['modified_by'], name='vm_history_modified_by'),
        ),
        migrations.AddIndex(
            model_name='vpnhistory',
            index=models.Index(fields=['modified_by'], name='vpn_history_modified_by'),
        ),
    ]
