# Generated by Django 2.2.14 on 2020-10-02 12:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0003_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('ipmi_host', models.GenericIPAddressField(null=True)),
                ('ipmi_credentials', models.CharField(max_length=128, null=True)),
                ('ipmi_username', models.CharField(max_length=250, null=True)),
                ('rage4_api_key', models.TextField(null=True)),
                ('rage4_email', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.AddField(
            model_name='router',
            name='credentials',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
