# Generated by Django 2.2.14 on 2020-10-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0004_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='management_interface',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='oob_interface',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='private_interface',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='public_interface',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='router_oob_interface',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
