# Generated by Django 2.2.17 on 2021-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0006_router_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archieved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['archieved'], name='project_archieved'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['closed'], name='project_closed'),
        ),
    ]
