# Generated by Django 2.2.17 on 2021-02-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0007_project_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='router',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='router_subnets',
                to='iaas.Router'),
        ),
    ]
