# Generated by Django 2.2.18 on 2021-03-31 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0008_router_subnets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmhistory',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='iaas.VM'),
        ),
    ]
