# Generated by Django 2.2.18 on 2021-05-21 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0009_cascade_vm_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpn',
            name='customer_subnets',
        ),
        migrations.RemoveField(
            model_name='vpn',
            name='local_subnet',
        ),
        migrations.AddField(
            model_name='vpn',
            name='traffic_selector',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('remote_subnet', models.CharField(max_length=49)),
                ('local_subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iaas.Subnet')),
                ('vpn', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='routes',
                    to='iaas.VPN',
                )),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['id'], name='route_id'),
        ),
    ]
