# Generated by Django 2.2 on 2021-07-29 15:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0011_project_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='dns',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='vpn_type',
            field=models.CharField(
                choices=[('site_to_site', 'site_to_site'), ('dynamic_secure_connect', 'dynamic_secure_connect')],
                default='site_to_site',
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='ike_public_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.CreateModel(
            name='VPNClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=64)),
                ('vpn', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='vpn_clients',
                    to='iaas.VPN',
                )),
            ],
            options={
                'db_table': 'vpn_client',
            },
        ),
        migrations.AddIndex(
            model_name='vpnclient',
            index=models.Index(fields=['id'], name='vpn_client_id'),
        ),
    ]
