# Generated by Django 2.2 on 2021-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0012_dynamic_vpn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('sku', models.CharField(max_length=250)),
                ('vm', models.ForeignKey(
                    null=True,
                    on_delete=models.deletion.CASCADE,
                    related_name='skus',
                    to='iaas.VM',
                )),
                ('vpn', models.ForeignKey(
                    null=True,
                    on_delete=models.deletion.CASCADE,
                    related_name='skus',
                    to='iaas.VPN',
                )),
            ],
            options={
                'db_table': 'bom',
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['id'], name='bom_id'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['created'], name='bom_created'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['quantity'], name='bom_quantity'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['sku'], name='bom_sku'),
        ),
    ]
