# Generated by Django 2.2 on 2021-08-23 16:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0015_snapshot_add_remove_subtree'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('customer_address', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('state', models.IntegerField(null=True)),
                ('vm_id', models.IntegerField()),
                ('snapshot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='history',
                    to='iaas.Snapshot',
                )),
            ],
            options={
                'db_table': 'snapshot_history',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='snapshothistory',
            index=models.Index(fields=['id'], name='snapshot_history_id'),
        ),
        migrations.AddIndex(
            model_name='snapshothistory',
            index=models.Index(fields=['created'], name='snapshot_history_created'),
        ),
        migrations.AddIndex(
            model_name='snapshothistory',
            index=models.Index(fields=['customer_address'], name='snapshot_history_cust_address'),
        ),
        migrations.AddIndex(
            model_name='snapshothistory',
            index=models.Index(fields=['deleted'], name='snapshot_history_deleted'),
        ),
        migrations.AddIndex(
            model_name='snapshothistory',
            index=models.Index(fields=['modified_by'], name='snapshot_history_modified_by'),
        ),
        migrations.AddIndex(
            model_name='snapshothistory',
            index=models.Index(fields=['project_id'], name='snapshot_history_project_id'),
        ),
        migrations.AddIndex(
            model_name='snapshothistory',
            index=models.Index(fields=['vm_id'], name='snapshot_history_vm_id'),
        ),
    ]
