# Generated by Django 2.2 on 2021-09-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0016_snapshot_history'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='project_archieved',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='archieved',
            new_name='archived',
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='parent',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='iaas.Snapshot',
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['archived'], name='project_archived'),
        ),
    ]
