# Generated by Django 2.2 on 2021-09-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0017_fix_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='vm',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='snapshots',
                to='iaas.VM',
            ),
        ),
    ]
