# Generated by Django 2.2 on 2021-11-08 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0020_backup_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
