# Generated by Django 2.2 on 2021-12-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0021_vm_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='ike_gateway_type',
            field=models.CharField(
                choices=[('public_ip', 'public_ip'), ('hostname', 'hostname')],
                default='public_ip',
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name='vpn',
            name='ike_gateway_value',
            field=models.TextField(default=''),
        ),
    ]
