# Generated by Django 2.2 on 2021-12-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0022_ike_gateway_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cloud_init',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vm',
            name='userdata',
            field=models.CharField(default='', max_length=16384),
            preserve_default=False,
        ),
    ]
