# Generated by Django 2.2 on 2022-02-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0025_backup_time_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['name'], name='backup_name'),
        ),
    ]
