# Generated by Django 2.2 on 2022-02-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0026_backup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='send_bill_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['send_bill_id'], name='project_send_bill_id'),
        ),
    ]
