# Generated by Django 2.2 on 2022-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0029_reseller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='member_id',
            field=models.IntegerField(null=True),
        ),
    ]
