# Generated by Django 2.2 on 2022-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0032_default_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpn',
            name='ike_mode',
        ),
        migrations.AddField(
            model_name='vpn',
            name='ike_local_identifier',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='vpn',
            name='ike_remote_identifier',
            field=models.CharField(max_length=253, null=True),
        ),
    ]
