# Generated by Django 2.2 on 2023-02-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0033_swan_vpn_ike_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='port',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
