# Generated by Django 2.2 on 2023-03-16 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0035_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='server',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='devices',
                to='iaas.Server',
            ),
        ),
    ]
