# Generated by Django 2.2 on 2023-05-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0037_order_storage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ipaddress',
            name='ip_address_cloud',
        ),
        migrations.RemoveIndex(
            model_name='subnet',
            name='subnet_cloud',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='cloud',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='cloud',
        ),
    ]
