# Generated by Django 2.2 on 2023-05-09 13:38

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0038_remvoe_cloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'resource',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ResourceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('modified_by', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'resource_history',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ResourceHistoryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sku', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'resource_history_line',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'resource_type',
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='resourcetype',
            index=models.Index(fields=['id'], name='resource_type_id'),
        ),
        migrations.AddField(
            model_name='resourcehistoryline',
            name='resource_history',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='lines',
                to='iaas.ResourceHistory',
            ),
        ),
        migrations.AddField(
            model_name='resourcehistory',
            name='resource',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='history_items',
                to='iaas.Resource',
            ),
        ),
        migrations.AddField(
            model_name='resource',
            name='parent',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='iaas.Resource',
            ),
        ),
        migrations.AddField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iaas.Project'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iaas.ResourceType'),
        ),
        migrations.AddField(
            model_name='backup',
            name='resource',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='iaas.Resource'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='resource',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='iaas.Resource'),
        ),
        migrations.AddField(
            model_name='virtualrouter',
            name='resource',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='iaas.Resource'),
        ),
        migrations.AddField(
            model_name='vm',
            name='resource',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='iaas.Resource'),
        ),
        migrations.AddField(
            model_name='vpn',
            name='resource',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='iaas.Resource'),
        ),
        migrations.AddIndex(
            model_name='resourcehistoryline',
            index=models.Index(fields=['id'], name='resource_history_line_id'),
        ),
        migrations.AddIndex(
            model_name='resourcehistory',
            index=models.Index(fields=['id'], name='resource_history_id'),
        ),
        migrations.AddIndex(
            model_name='resourcehistory',
            index=models.Index(fields=['state'], name='resource_history_state'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['id'], name='resource_id'),
        ),
    ]
