# Generated by Django 2.2 on 2023-06-06 11:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0039_resource_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name', models.CharField(max_length=128)),
                ('size', models.IntegerField()),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iaas.Resource')),
            ],
            options={
                'db_table': 'ceph',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='ceph',
            index=models.Index(fields=['id'], name='ceph_id'),
        ),
        migrations.AddIndex(
            model_name='ceph',
            index=models.Index(fields=['name'], name='ceph_name'),
        ),
        migrations.AddIndex(
            model_name='ceph',
            index=models.Index(fields=['size'], name='ceph_size'),
        ),
    ]
