# Generated by Django 2.2 on 2023-08-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0040_ceph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcehistory',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourcehistoryline',
            name='resource_history',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='virtualrouter',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='vpn',
            name='resource',
        ),
        migrations.AddField(
            model_name='bom',
            name='resource',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='skus',
                to='iaas.Resource',
            ),
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='resources',
                to='iaas.Project',
            ),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='state',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='Ceph',
        ),
        migrations.DeleteModel(
            name='ResourceHistory',
        ),
        migrations.DeleteModel(
            name='ResourceHistoryLine',
        ),
    ]
