# Generated by Django 2.2 on 2024-07-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0041_delete_ceph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceType',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='mac_address',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
