# Generated by Django 2.2 on 2024-10-02 14:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaas', '0042_vm_ip_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('cidrs', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('member_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('version', models.IntegerField(default=4)),
            ],
            options={
                'db_table': 'ip_address_group',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='ipaddressgroup',
            index=models.Index(fields=['id'], name='ip_addr_group_id'),
        ),
        migrations.AddIndex(
            model_name='ipaddressgroup',
            index=models.Index(fields=['deleted'], name='ip_addr_group_deleted'),
        ),
        migrations.AddIndex(
            model_name='ipaddressgroup',
            index=models.Index(fields=['member_id'], name='ip_addr_group_member_id'),
        ),
        migrations.AddIndex(
            model_name='ipaddressgroup',
            index=models.Index(fields=['name'], name='ip_addr_group_name'),
        ),
        migrations.AddIndex(
            model_name='ipaddressgroup',
            index=models.Index(fields=['version'], name='ip_addr_group_version'),
        ),
    ]
